### ISSUE TITLE
syphon server texture / multi cam switching

### ISSUE THREAD

**Issue by brycelynch** [Syphon/Unity3D#10]
I have multiple cameras set up with a simple switcher script in Unity driven by keyboard input.  Each camera has a syhpon server texture attached.  I'm recording the syphon feed but getting separate feeds for each camera.  Is there a relatively simple solution to modify the server texture script so that the syphon feed is only sending the active camera in the scene?  Thanks for any help!

**Comment by rsodre** [comment]
you could have just one offscreen camera with the syphon texture, pointing to a square textured with the contents of the other cameras.

**Comment by brycelynch** [comment]
Great idea!  Thanks!  :)
