### ISSUE TITLE
Support Unity 5

### ISSUE THREAD

**Issue by 13kot** [Syphon/Unity3D#11]
Hello!
Please tell me when we can expect a new version Syphon plugin for Unity 3D ver 5.02?

**Comment by budezllc** [comment]
Same.. it works but I'm getting a lot of log warnings about shader variants ex: Failed to create a shader variant in 'Alpha-Diffuse02'. You probably have precompiled shader asset from an old Unity version.

**Comment by brianchasalow** [comment]
try the latest git commit

**Comment by budezllc** [comment]
Thanks a ton Brian, will do this today.

**Comment by OskarGroth** [comment]
Is there any way to use SyphonClientTexture on a canvas? The last commit (a1c423ae4e6edcde2efe871d2a0f403d639fe2af) indicates this is now supported, but I'm unable to figure out how. When applying it to a RawImage, there's an error about "No Renderer attached to the 'RawImage' game object". When I add a Mesh Renderer, I get NullReferenceExeption on line 83 in SyphonClientTexture.cs:

				matArray[i].mainTexture = clientObject.AttachedTexture;	

Not sure how to proceed.

**Comment by brianchasalow** [comment]
this is possible, you need to inherit from SyphonClientTexture and just override the ApplyTexture method.
I should probably make a sample showing how to do this.
