### ISSUE TITLE
Client flicker when using unity syphon server in the unity editor.

### ISSUE THREAD

**Issue by caelshadowhunter** [Syphon/Unity3D#13]
Hi,
I've got an issue where the client image flickers, when a unity project including a Syphon server is 'played' in the Unity editor. No issue when using the built unity project. I'm on a system running:
- OSX 10.9.2 (also tested on 10.10)
- Unity 5.1.1.1f1
- Latest version of the Unity Syphon plugin (Beta 2 a16 - pulled from Git repo yesterday).

**Comment by brianchasalow** [comment]
yeahh, this is a known issue. can't fix it til Unity provides gl context callbacks- but it sounds like it's something they're working on. We'll see how soon they can fix it so I can improve this.
