### ISSUE TITLE
Glitchy video using Custom Resolution Server (Unity 5)

### ISSUE THREAD

**Issue by Ubik3D** [Syphon/Unity3D#14]
Hi Brian
I get a strange glitch with the Custom Resolution server texture.

It gives me a very glitchy output, like this:
https://dl.dropboxusercontent.com/u/30356710/syphonunityglitch.mov 		

(and for some reason the realtime result is even glitchier than this saved video of it)

The video is from a clean new unity project with only the latest Syphon unity package imported.
However, the scripts have been modified by the automatic prompt that updates the API.

I’m running Unity 5.13f1 Personal

I also tried it on a different computer than mine with the same result.

Can you see what the problem is?

I’m basing a major art project on getting a fixed 3200x3200 resolution from Unity, so any help that you can provide me with is of great help!

With kind regards,
Daniel

**Comment by brianchasalow** [comment]
solved with https://github.com/syphon/unity3d/tree/fixes/5.2RenderAPI i believe. reopen if any more issues!
