### ISSUE TITLE
syphon input tiling in Unity

### ISSUE THREAD

**Issue by jhoepffner** [Syphon/Unity3D#15]
Hello,
When I prepare a texture in Unity, using UV map to have one picture or one movie in part of surface, it works, when I replace it by syphon client texture, it's tiled to cover all the surface.
There is a way to avoid that?
Thank you;
Jacques Hoepffner

**Comment by brianchasalow** [comment]
Yes, but it depends how you're setting up your UV offsets - on the material
itself? If so, make a new script that inherits from SyphonClientTexture and
overrides ApplyVideoTexture, and apply the same UV offsets when the client
texture gets attached to the material. You might also want to change the
wrapMode of the client texture.
Brian

**Comment by jhoepffner** [comment]
Thank you for your quick answer, I will try to do what you say, but I’m not sure to understand everything!

I will come back with more answer and precisions later.

All the best
–––––––––––––––––––––––––––––––––––––––
Jacques Hoepffner
6, passage Dagorno
75020 Paris
cell +33 6 83 23 90 62
tel +33 1 44 93 39 27
jacques@hoepffner.info
http://www.hoepffner.info

**Comment by jhoepffner** [comment]
Hello,

With your help, I found a very easy solution (for me), I just replaced « repeat » by « clamp » in the « Syphon Client texture » script and voilà…

My goal is to have a 3D mapper for moving and rotating screen in Isadora. The repeat behavior was the last problem to solve. Now I am ready to use it for performance.

Thank you,
Jacques

**Comment by jhoepffner** [comment]
Hello,

I have another question, when I return te image from my Unity camera to Isadora by Syphon, if I use Syphon Server Texture, it works flawlessly, but with Syphon Server Texture Custom Resolution, if I move a parameter in Unity (like rotating the plane holding the texture), there is some white ghost showing in the image reception in Isadora, do you have any idea where is the problem?

Thank you
–––––––––––––––––––––––––––––––––––––––
Jacques Hoepffner
6, passage Dagorno
75020 Paris
cell +33 6 83 23 90 62
tel +33 1 44 93 39 27
jacques@hoepffner.info
http://www.hoepffner.info

**Comment by brianchasalow** [comment]
try the latest release as of 2 minutes ago:
https://github.com/Syphon/Unity3D/releases/tag/a17

**Comment by jhoepffner** [comment]
Hello,

You are tooooo quick! It work perfectly

Thank you,

–––––––––––––––––––––––––––––––––––––––
Jacques Hoepffner
6, passage Dagorno
75020 Paris
cell +33 6 83 23 90 62
tel +33 1 44 93 39 27
jacques@hoepffner.info
http://www.hoepffner.info
