### ISSUE TITLE
Black texture

### ISSUE THREAD

**Issue by piotrus04** [Syphon/Unity3D#19]
Hi all, 
If i simply launch the unity server scene, and check the picture into syphon simple client, 
the result is just black.
it never happened to me before.
in the simple client app, i see that the resolution of the picture is the same as my unity game window.
And i can see the framerate fluctuating.
OS x Yosemite. 10.10.4
Unity 5.3.1
It is urgent, do you have any idea about this issue ?

**Comment by vade** [comment]
look at #17
