### ISSUE TITLE
Unity 5 Render Texture Support?

### ISSUE THREAD

**Issue by budezllc** [Syphon/Unity3D#9]
I have two cameras. A front camera with an plane displaying a render texture from a third hidden camera at 0 and the main camera at -1 depth. Syphon does not output the front camera, only the main camera. Is this a bug or just unsupported feature?

**Comment by brianchasalow** [comment]
You should be able to output multiple cameras simultaneously.

**Comment by budezllc** [comment]
Thannks Brian. I went back in and messed around and realized I needed the syphon script on the front most depth camera instead of what I use to call main. Works perfectly thanks for the reply.
